source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Bean_Example', :exclusive => true do
  pod "Bean", :path => "../"
end

target 'Bean_Tests', :exclusive => true do
  pod "Bean", :path => "../"

  
end
